### ISSUE TITLE
无法正常创建门

### ISSUE THREAD

**Issue by chasiopen** [LovesAsuna/Lock#2]
**Describe the bug(描述bug)**
好像依然不太好用（///////）
相比于上次貌似只是后台不报错了，
依然无法创建正常的门。
写完
lock
100

之后，就直接变成了下面截图的样子，只有第三行发生变化。也无法通过门。

服务端 paper 1.14.4

**Expected behavior(错误发生前执行的操作)**
正常操作

**StackTrace(后台错误报告,截图或直接复制)**
没有报错

**Screenshots(图片)**

![1](https://user-images.githubusercontent.com/35827956/78413930-424a9e80-764c-11ea-845b-6b75282f6e70.png)

**Comment by LovesAsuna** [comment]
这种情况来看我觉得是其他插件的干扰？尝试单独测试插件效果？
它是通过判断第一行的内容来识别的，既然第一行内容都没变，那进不去就是自然的

**Comment by chasiopen** [comment]
1.我在我一个较新的服务端里测试了，能创建门，但是过不去，而且可以破坏掉门
![图片1](https://user-images.githubusercontent.com/35827956/78426655-54f1c180-76a6-11ea-8189-0a48cb81fbf5.png)


创建门时，后台报错：
[18:52:12] [Server thread/INFO]: ========================= printStackTrace =========================
[18:52:12] [Server thread/INFO]: Exception Type ?
[18:52:12] [Server thread/INFO]: java.lang.NoSuchMethodException: net.minecraft.server.v1_14_R1.WorldServer.getTileEntity(net.minecraft.server.v1_14_R1.BlockPosition)
[18:52:12] [Server thread/INFO]:
[18:52:12] [Server thread/INFO]:
[18:52:12] [Server thread/INFO]: Package java  ?
[18:52:12] [Server thread/INFO]:   ? at Class Class , Method getDeclaredMethod. (null, Line -1)
[18:52:12] [Server thread/INFO]:
[18:52:12] [Server thread/INFO]: Package org.sct.lock.util  ?
[18:52:12] [Server thread/INFO]:   ? at Class HoverTextAPI , Method <init>. (HoverTextAPI.java, Line 64)
[18:52:12] [Server thread/INFO]:   ? at Class SIgnProcessUtil , Method <clinit>. (SIgnProcessUtil.java, Line 22)
[18:52:12] [Server thread/INFO]:
[18:52:12] [Server thread/INFO]: Package org.sct.lock  ?
[18:52:12] [Server thread/INFO]:   ? at Class SignChangeListener , Method onSignChange. (SignChangeListener.java, Line 40)
[18:52:12] [Server thread/INFO]:
[18:52:12] [Server thread/INFO]: Package sun  ?
[18:52:12] [Server thread/INFO]:   ? at Class NativeMethodAccessorImpl , Method invoke0. (null, Line -2)
[18:52:12] [Server thread/INFO]:   ? at Class NativeMethodAccessorImpl , Method invoke. (null, Line -1)
[18:52:12] [Server thread/INFO]:   ? at Class DelegatingMethodAccessorImpl , Method invoke. (null, Line -1)
[18:52:12] [Server thread/INFO]:
[18:52:12] [Server thread/INFO]: Package java.lang  ?
[18:52:12] [Server thread/INFO]:   ? at Class Method , Method invoke. (null, Line -1)
[18:52:12] [Server thread/INFO]:
[18:52:12] [Server thread/INFO]: Package org.bukkit.plugin  ?
[18:52:12] [Server thread/INFO]:   ? at Class JavaPluginLoader$1 , Method execute. (JavaPluginLoader.java, Line 316)
[18:52:12] [Server thread/INFO]:
[18:52:12] [Server thread/INFO]: Package org.bukkit  ?
[18:52:12] [Server thread/INFO]:   ? at Class RegisteredListener , Method callEvent. (RegisteredListener.java, Line 70)
[18:52:12] [Server thread/INFO]:   ? at Class SimplePluginManager , Method fireEvent. (SimplePluginManager.java, Line 529)
[18:52:12] [Server thread/INFO]:   ? at Class SimplePluginManager , Method callEvent. (SimplePluginManager.java, Line 514)
[18:52:12] [Server thread/INFO]:
[18:52:12] [Server thread/INFO]: Package net.minecraft.server  ?
[18:52:12] [Server thread/INFO]:   ? at Class PlayerConnection , Method a. (PlayerConnection.java, Line 2381)
[18:52:12] [Server thread/INFO]:   ? at Class PacketPlayInUpdateSign , Method a. (SourceFile, Line 44)
[18:52:12] [Server thread/INFO]:   ? at Class PacketPlayInUpdateSign , Method a. (SourceFile, Line 10)
[18:52:12] [Server thread/INFO]:   ? at Class PlayerConnectionUtils , Method lambda$0. (PlayerConnectionUtils.java, Line 19)
[18:52:12] [Server thread/INFO]:   ? at Class TickTask , Method run. (SourceFile, Line 18)
[18:52:12] [Server thread/INFO]:   ? at Class IAsyncTaskHandler , Method executeTask. (SourceFile, Line 144)
[18:52:12] [Server thread/INFO]:   ? at Class IAsyncTaskHandlerReentrant , Method executeTask. (SourceFile, Line 23)
[18:52:12] [Server thread/INFO]:   ? at Class IAsyncTaskHandler , Method executeNext. (SourceFile, Line 118)
[18:52:12] [Server thread/INFO]:   ? at Class MinecraftServer , Method aX. (MinecraftServer.java, Line 910)
[18:52:12] [Server thread/INFO]:   ? at Class MinecraftServer , Method executeNext. (MinecraftServer.java, Line 903)
[18:52:12] [Server thread/INFO]:   ? at Class IAsyncTaskHandler , Method awaitTasks. (SourceFile, Line 127)
[18:52:12] [Server thread/INFO]:   ? at Class MinecraftServer , Method sleepForTick. (MinecraftServer.java, Line 887)
[18:52:12] [Server thread/INFO]:   ? at Class MinecraftServer , Method run. (MinecraftServer.java, Line 820)
[18:52:12] [Server thread/INFO]:
[18:52:12] [Server thread/INFO]: Package java  ?
[18:52:12] [Server thread/INFO]:   ? at Class Thread , Method run. (null, Line -1)
[18:52:12] [Server thread/INFO]: ========================= printStackTrace =========================
[18:52:12] [Server thread/INFO]: ========================= printStackTrace =========================
[18:52:12] [Server thread/INFO]: Exception Type ?
[18:52:12] [Server thread/INFO]: java.lang.NullPointerException
[18:52:12] [Server thread/INFO]:
[18:52:12] [Server thread/INFO]:
[18:52:12] [Server thread/INFO]: Package org.sct.lock.util  ?
[18:52:12] [Server thread/INFO]:   ? at Class HoverTextAPI , Method getChatModifier. (HoverTextAPI.java, Line 139)
[18:52:12] [Server thread/INFO]:   ? at Class HoverTextAPI , Method saveText. (HoverTextAPI.java, Line 92)
[18:52:12] [Server thread/INFO]:   ? at Class SIgnProcessUtil , Method lambda$processConditions$0. (SIgnProcessUtil.java, Line 105)
[18:52:12] [Server thread/INFO]:
[18:52:12] [Server thread/INFO]: Package org.bukkit.craftbukkit.v1_14_R1  ?
[18:52:12] [Server thread/INFO]:   ? at Class CraftTask , Method run. (CraftTask.java, Line 81)
[18:52:12] [Server thread/INFO]:   ? at Class CraftScheduler , Method mainThreadHeartbeat. (CraftScheduler.java, Line 394)
[18:52:12] [Server thread/INFO]:
[18:52:12] [Server thread/INFO]: Package net.minecraft.server  ?
[18:52:12] [Server thread/INFO]:   ? at Class MinecraftServer , Method b. (MinecraftServer.java, Line 1023)
[18:52:12] [Server thread/INFO]:   ? at Class DedicatedServer , Method b. (DedicatedServer.java, Line 396)
[18:52:12] [Server thread/INFO]:   ? at Class MinecraftServer , Method a. (MinecraftServer.java, Line 971)
[18:52:12] [Server thread/INFO]:   ? at Class MinecraftServer , Method run. (MinecraftServer.java, Line 816)
[18:52:12] [Server thread/INFO]:
[18:52:12] [Server thread/INFO]: Package java  ?
[18:52:12] [Server thread/INFO]:   ? at Class Thread , Method run. (null, Line -1)
[18:52:12] [Server thread/INFO]: ========================= printStackTrace =========================

2.可能是插件的影响，我正在排查。

**Comment by LovesAsuna** [comment]
可以破坏掉门是owner的权限，但是从这个报错上看我找不出我写法上的错误（毕竟这个版本我在1.8 1.12 1.14 1.15的版本上都实际测试过）。通过门时是否有报错呢？是否有在潜行的状态下才右键？因为这个版本的收费门采用的是新型的信息储存，所以在储存和读取条件这块可能还会有不完善的地方，见谅

**Comment by chasiopen** [comment]
1.无法创建门是我疏忽了插件里的世界设置，是我的问题。
2.创建门之后，过不去。shift右键没有反应，用红石能激活门好像和配置里的不符合，激活门后进出也不扣钱。
3.而且别人可以破坏自己放的木牌。

**Comment by LovesAsuna** [comment]
owner进门不扣钱也可以拆门,其他问题还有待考究

**Comment by LovesAsuna** [comment]
![64B%G3}0{49%GUJHD`LJ2@F](https://user-images.githubusercontent.com/32810896/78450092-a605b380-76ae-11ea-90ae-63f8d549d703.png)
激活禁用的功能在1.15没有问题[挠头]
阻止破坏也没问题(方块牌子门都不能)
![E2%MO57J%T~Y1V$REGINHNQ](https://user-images.githubusercontent.com/32810896/78450182-54a9f400-76af-11ea-8bfe-fa9e71af31f9.png)

**Comment by chasiopen** [comment]
能不能测试一下1.14.4的paper spigot服?是不是不兼容？

**Comment by LovesAsuna** [comment]
理论上来讲spigot能用paper就能用，刚刚实际测试两个都能用

另外之前的只显示第三行的问题正如你所说是世界禁用导致，这里存在一些逻辑问题导致了显示第三行，现在添加了这个提示并修改了逻辑
![0}93AGM%%A 9_WL9}%@A`8V](https://user-images.githubusercontent.com/32810896/78450461-478e0480-76b1-11ea-85ce-faf55f637a4f.png)

**Comment by chasiopen** [comment]
...我其实挺急的也没有什么思路，但是我刚刚测试的时候发现了这个报错：

[20:11:58 ERROR]: Could not pass event PlayerInteractEvent to Lock v1.5.0-Alpha
java.lang.IllegalArgumentException: value already present: null
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:287) ~[patched_1.14.4.jar:git-Paper-243]
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:262) ~[patched_1.14.4.jar:git-Paper-243]
        at org.sct.lock.util.function.LockUtil.getLocation(LockUtil.java:48) ~[?:?]
        at org.sct.lock.listener.PlayerInteractListener.onPlayerInteract(PlayerInteractListener.java:60) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor518.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-243]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:443) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-243]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

希望能够看出问题所在吧。

**Comment by LovesAsuna** [comment]
这个问题无关紧要，与无法通过无关,实际不行就放弃吧

**Comment by chasiopen** [comment]
其实您的插件已经成为我服务器副本里的一个不可缺少的部分，我再试试吧

**Comment by LovesAsuna** [comment]
不嫌弃我的插件真实万分感谢。我会竭尽所能解决你的问题XD

**Comment by chasiopen** [comment]
我用最新的 [paper1.14.4构筑](https://papermc.io/ci/job/Paper-1.14/) 重新做了一个服务器，只有一些基础的插件，用纯净的MC1.14.4客户端进入，发现了同样的问题，后台也没有报错。

能够正常创建门，但是无法通过，shift右键没有反应。希望作者能够兼容一下这个版本，万分感谢！

**Comment by LovesAsuna** [comment]
试试删除配置重新生成再配置？或者我到你服务器看看

**Comment by chasiopen** [comment]
能不能留一个QQ方便联系一下？我的QQ 1467263004

**Comment by LovesAsuna** [comment]
625924077
