### ISSUE TITLE
修复之后载入插件报错

### ISSUE THREAD

**Issue by RainLong65** [LovesAsuna/Lock#4]
只有门的主人可以进入，其他人会显示你有三秒的等待时间，控制台报错：[Server thread/ERROR]: Could not pass event PlayerInteractEvent to Lock v1.5.3-Alpha
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:437) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:431) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1238) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:885) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.IllegalArgumentException: value already present: null
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:287) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at com.google.common.collect.HashBiMap.put(HashBiMap.java:262) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.sct.lock.util.function.LockUtil.setLocation(LockUtil.java:48) ~[?:?]
        at org.sct.lock.listener.PlayerInteractListener.onPlayerInteract(PlayerInteractListener.java:55) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor379.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        ... 19 more[http://chuantu.xyz/t6/729/1587481296x2890211979.png](url)

**Comment by LovesAsuna** [comment]
三秒等待时间是新功能，上上个版本就添加的，为了确认以及展示条件

**Comment by RainLong65** [comment]
可是除了门的主人其他玩家还是无法进入呀？
服务器地址：p-c9.polarstar.cc:48401

**Comment by RainLong65** [comment]
摁下shift之后然后显示你有三秒的等待时间，然后后台报错，人物还是在原地，没有进去

**Comment by LovesAsuna** [comment]
试了几次都会出现上述报错吗？如果把门换个地方创建呢？

**Comment by RainLong65** [comment]
是的，在其他世界也会报错，只有创建门的主人通过不会报错，其他玩家尝试通过是会出现上述一样的报错

**Comment by LovesAsuna** [comment]
这个大概不会报错，能不能进还不知道
[Lock.zip](https://github.com/LovesAsuna/Lock/files/4511028/Lock.zip)

**Comment by RainLong65** [comment]
老样子没有解决，还是报错。。。。

**Comment by RainLong65** [comment]
[00:46:30] [Server thread/ERROR]: Could not pass event PlayerAccessLockDoorEvent to Lock v1.5.3-Alpha
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.sct.lock.listener.PlayerInteractListener.callEvent(PlayerInteractListener.java:128) ~[?:?]
        at org.sct.lock.listener.PlayerInteractListener.onPlayerInteract(PlayerInteractListener.java:106) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:437) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:431) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1238) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NoSuchMethodError: org.sct.plugincore.PluginCoreAPI.getEcoAPI()Lorg/sct/plugincore/api/EcoAPI;
        at org.sct.lock.listener.LockDoorAccessListener.onAccess(LockDoorAccessListener.java:84) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        ... 28 more
[00:46:30] [Server thread/ERROR]: Could not pass event PlayerAccessLockDoorEvent to Lock v1.5.3-Alpha
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.sct.lock.listener.PlayerInteractListener.callEvent(PlayerInteractListener.java:128) ~[?:?]
        at org.sct.lock.listener.PlayerInteractListener.onPlayerInteract(PlayerInteractListener.java:106) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:437) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:431) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1238) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NoSuchMethodError: org.sct.plugincore.PluginCoreAPI.getEcoAPI()Lorg/sct/plugincore/api/EcoAPI;
        at org.sct.lock.listener.LockDoorAccessListener.onAccess(LockDoorAccessListener.java:84) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[Spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        ... 28 more

**Comment by LovesAsuna** [comment]
这个大概不会报错，能不能进还不知道
https://c-t.work/s/0875141c230f47 取件码：zi9dav（24小时内有效）

**Comment by LovesAsuna** [comment]
这里的问题是你没有更新PluginCore

**Comment by RainLong65** [comment]
更新之后可以正常使用了，麻烦你了谢谢！
